---
##########################################################################################
#                                                                                        #
#                       Pre-commit configuration file                                    #
#                                                                                        #
#                                                                                        #
# See https://pre-commit.com for more information                                        #
# See https://pre-commit.com/hooks.html for more hooks                                   #
#                                                                                        #
# To install the git pre-commit hook run:                                                #
#   pre-commit install                                                                   #
#   pre-commit autoupdate                                                                #
# To update the pre-commit hooks run:                                                    #
#   pre-commit install --install-hooks -t pre-commit -t commit-msg                       #
# To run all hooks against current changes in your repository                            #
#   pre-commit run --all-files                                                           #
# If you wish to execute an individual hook use pre-commit run <hook_id>. Example:       #
#   pre-commit run black                                                                 #
#                                                                                        #
##########################################################################################

default_language_version:
    python: python3
default_stages: [commit, push]
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: fix-byte-order-marker
            name: fix-byte-order-marker
            description: removes UTF-8 byte order marker
          - id: trailing-whitespace
            name: trailing-whitespace
            description: Trims trailing whitespace
            args: [--markdown-linebreak-ext=md]
          - id: check-case-conflict
            name: check-case-conflict
            description: Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
          - id: end-of-file-fixer
            name: end-of-file-fixer
            description: Makes sure files end in a newline and only a newline
          - id: mixed-line-ending
            name: mixed-line-ending
            description: Replaces or checks mixed line ending
          - id: check-ast
            name: check-ast
            description: Simply check whether files parse as valid python
          - id: debug-statements
            name: debug-statements
            description: Check for debugger imports and py37+ breakpoint() calls in python source
          - id: requirements-txt-fixer
            name: requirements-txt-fixer
            description: Sorts entries in requirements.txt and removes incorrect entries
          - id: check-merge-conflict
            name: check-merge-conflict
            description: Check for files that contain merge conflict strings
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-check-mock-methods
            name: check-mock-methods
            description: Prevent common mistakes of assert mck.not_called(), assert mck.called_once_with(...) and mck.assert_called.
          - id: python-use-type-annotations
            name: python-use-type-annotations
            description: Enforce that python3.6+ type annotations are used instead of type comments
          - id: python-check-blanket-noqa
            name: python-check-blanket-noqa
            description: Enforce that noqa annotations always occur with specific codes.
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            name: mypy - static type checker for Python
            description: Static type checker for Python
            files: ^src/
            exclude: ^tests/
            args: [--ignore-missing-imports]
            additional_dependencies: [types-all]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
            name: add-trailing-comma
            description: Automatically add trailing commas to calls and literals.
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.4.8
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
        - id: black
          name: black - consistent Python code formatting
          description: The uncompromising Python code formatter
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
          - id: pyupgrade
            name: pyupgrade - upgrade syntax for newer versions of the language
            description: Automatically upgrade syntax for newer versions of the language
            args: [--py36-plus]
##########################################################################################
# Documentation
##########################################################################################
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.17
      hooks:
          - id: mdformat
            name: mdformat - Markdown formatter that can be used to enforce a consistent style in Markdown files
            description: Markdown formatter that can be used to enforce a consistent style in Markdown files
            additional_dependencies:
              - mdformat-black
              - mdformat-beautysh
            exclude: CHANGELOG.md
    - repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.1
      hooks:
          - id: darglint
            name: darglint - Python documentation linter
            description: A python documentation linter which checks that the docstring description matches the definition.
            args: ["-z", long]
